# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.16.1'

### Importing the dataset

## Part 1 - Data Preprocessing

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X  = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values

print(X, Y, sep='\n')

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [5]:
from sklearn.preprocessing import LabelEncoder

X[:, 2] = LabelEncoder().fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

### Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(X_train)

[[ 0.98497008 -0.56987189 -0.5731713  ...  0.64198477  0.96683535
  -0.76862426]
 [ 0.98497008 -0.56987189 -0.5731713  ...  0.64198477 -1.03430227
  -1.39359887]
 [ 0.98497008 -0.56987189 -0.5731713  ... -1.55766936  0.96683535
  -1.49739308]
 ...
 [ 0.98497008 -0.56987189 -0.5731713  ...  0.64198477 -1.03430227
   1.41400417]
 [-1.01525927 -0.56987189  1.74467913 ...  0.64198477  0.96683535
   0.84625811]
 [-1.01525927  1.75478035 -0.5731713  ...  0.64198477 -1.03430227
   0.32689267]]


## Part 2 - Building the ANN

### Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
print(ann.layers.__len__())

2


### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [46]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [47]:
ann.fit(X_train, Y_train, batch_size=32, epochs=100)

Epoch 1/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - accuracy: 0.8684 - loss: 0.3216
Epoch 2/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - accuracy: 0.8636 - loss: 0.3317
Epoch 3/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.8708 - loss: 0.3209
Epoch 4/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - accuracy: 0.8643 - loss: 0.3249
Epoch 5/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 686us/step - accuracy: 0.8643 - loss: 0.3261
Epoch 6/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.8654 - loss: 0.3292
Epoch 7/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step - accuracy: 0.8662 - loss: 0.3257
Epoch 8/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.8689 - loss: 0.3275
Epoch 9/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - accuracy: 0.8569 - loss: 0.3442
Epoch 10/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step - accuracy: 0.8636 - loss: 0.3257
Epoch 11/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - accuracy: 0.8710 - loss: 0.3263
Epoch 12/100
219/21

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [50]:
print(ann.predict(ss.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[False]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [52]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred), 1), Y_test.reshape(len(Y_test), 1)), 1))

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 566us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


### Making the Confusion Matrix

In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred))

[[2271  108]
 [ 294  327]]
0.866
